import type { Metadata } from "next";
import { Fredoka, Playfair_Display } from "next/font/google"; // Modern Font Optimization
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

export const metadata: Metadata = {
  title: "IMDB Movie Insider",
  description: "Generated by Yash Mankar AraeneaCLI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${fredoka.variable} ${playfair.variable} antialiased min-h-screen bg-[#0E0E11]`}
      >
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
